name: Cargo tests

on: [ push, pull_request ]

jobs:
  cargo_test:
    runs-on: macos-latest

    steps:
     - uses: actions/checkout@v2
     - uses: actions-rs/toolchain@v1
       with:
         toolchain: stable
         target: wasm32-unknown-unknown
     - run: ./run-test.sh
